### ISSUE TITLE
Version 

### ISSUE THREAD

**Issue by irrelevantdotcom** [nimmis/docker-spigot#11]
Fetches and compiles latest correctly., but then attempts to copy /target/spigot-1.8.*.jar 
As currently this is on 1.10.x, this fails.
(Editing /spigot_init.sh works...)

**Comment by nimmis** [comment]
You must have an old version of nimmis/spigot as this has been fixed and spigot_init.sh is no loger used. Try a **docker pull nimmis/spigot** and run it again. Then it should work, please read re readme as there are new commands added after the version you are using.
