### ISSUE TITLE
Invalid initial heap size: -Xms

### ISSUE THREAD

**Issue by Kianda** [nimmis/docker-spigot#14]
root@kianda-vps:~# docker exec 9276bf483cdf mc_log
Abort with CTRL-C
Invalid initial heap size: -Xms
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

How can I fix this? Thanks!

**Comment by nimmis** [comment]
Fixed, was a bug when MC_MINMEM was not defined.
do a
**docker pull nimmis/spigot**
and try again and everything should work
