### ISSUE TITLE
Server does not restart on "/stop"

### ISSUE THREAD

**Issue by ajthemacboy** [nimmis/docker-spigot#18]
The server will not restart automatically once it has stopped. Perhaps this is intended behavior; if so, how can I change it so it does restart?

I have tried adding `autorestart=true` in `/etc/supervisor/conf.d/spigot.conf` with no luck.

**Comment by nimmis** [comment]
There was a bug in the script handling the /etc/init.d/minecraft-server as it assumed the start and stop is made only with supervisorctl. I have written a new wrapper that handles the stop command from within minecraft. Fixing this also fixed the autostart so if someone still need the old way there is a new configuration variable for disable the autorestart function.
