### ISSUE TITLE
Question: How do you send command to the Spigot server?

### ISSUE THREAD

**Issue by BirkhoffLee** [nimmis/docker-spigot#19]
*In https://github.com/nimmis/docker-spigot/blob/master/rootfs/etc/init.d/minecraft_server#L129*

I don't understand how this works. Do I need a plugin to do that or is it a Spigot built-in feature for running a command outside the Spigot console?

**Comment by BirkhoffLee** [comment]
Oh!!! You are genius! I saw it! Thanks!

https://github.com/nimmis/docker-spigot/blob/master/rootfs/etc/init.d/minecraft_server#L273

**Comment by penut85420** [comment]
You save my life, what a magic command
