### ISSUE TITLE
Build spigot jar in docker build as opposed to docker run

### ISSUE THREAD

**Issue by Hout** [nimmis/docker-spigot#2]
With the risk of labouring the obvious: the nature of a docker image is that it is build in the `docker build` command and run with the `docker run` command. Building the jar in the spigot_init shell script in `docker run` is against the nature of docker and will confuse people.

Including the build of the spigot.jar in a separate image build simplifies updating the jar.

**Comment by nimmis** [comment]
Updated the README with information why the precompiled version can't be distributet with the image

**Comment by Hout** [comment]
Aha! Thx again :+1:
