### ISSUE TITLE
Error response from daemon: oci runtime error

### ISSUE THREAD

**Issue by stemda** [nimmis/docker-spigot#21]
When I try to create a new container with the following command 

`docker run -d -p 25565:25565 -e EULA=true nimmis/spigot -e MC_MAXMEM=3g -3 MC_MINMEM=512m -v /var/www/docker/minecraft:/minecraft -e SPIGOT_UID=1001`

I get this error message. 

`docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \"-e\": executable file not found in $PATH".`

Has anyone run into the same / a similar problem?

**Comment by nimmis** [comment]
**nimmis/spigot** should be the last entry on the command line also you should have -e and not -3

corret command should be

`docker run -d -p 25565:25565 -e EULA=true -e MC_MAXMEM=3g -e  MC_MINMEM=512m -v /var/www/docker/minecraft:/minecraft -e SPIGOT_UID=1001 nimmis/spigot`

**Comment by stemda** [comment]
Thanks for you quick response. Seems I'm a little more hung over than I thought. :)
