### ISSUE TITLE
Cannot select version to compile

### ISSUE THREAD

**Issue by CoderFX** [nimmis/docker-spigot#24]
Tried "-e SPIGOT_VER XX" where XX was many variations, like 1.8, 1.9.2, etc. all of them end up in failing 

```
Unable to find image '1.8:latest' locally
docker: Error response from daemon: repository 1.8 not found: does not exist or no pull access.
See 'docker run --help'.
```

**Comment by nimmis** [comment]
you are missing a equal sign, to select version 1.8 you should add **-e SPIGOT_VER=1.8**
