### ISSUE TITLE
Server fails to start

### ISSUE THREAD

**Issue by minexew** [nimmis/docker-spigot#25]
Host OS: CentOS 7 kernel 3.10.0-693.5.2.el7.x86_64 (setenforce 0)
Docker version 1.12.6, build 85d7426/1.12.6

Container created using:
```
root@host# docker run -d -p 25565:25565 -e EULA=true --name spigot -v /srv/spigot-data/:/minecraft nimmis/spigot
```

Builds fine, but when it's supposed to start:

```
dockerd-current[21038]: *** open logfile
dockerd-current[21038]: *** Run files in /etc/my_runonce/
dockerd-current[21038]: *** Run files in /etc/my_runalways/
dockerd-current[21038]: *** Running /etc/my_runalways/00_minecraft_owner...
dockerd-current[21038]: *** Running /etc/my_runalways/50_do_build_spigot...
dockerd-current[21038]: Setting version to latest
dockerd-current[21038]: *** Running /etc/my_runalways/90_eula...
dockerd-current[21038]: *** Running /etc/rc.local...
dockerd-current[21038]: *** Booting supervisor daemon...
dockerd-current[21038]: *** Supervisor started as PID 30
dockerd-current[21038]: 2017-12-05 23:11:50,175 CRIT Set uid to user 0
dockerd-current[21038]: *** Started processes via Supervisor......
dockerd-current[21038]: crond                            RUNNING   pid 34, uptime 0:00:04
dockerd-current[21038]: spigot                           BACKOFF   Exited too quickly (process log may have details)
dockerd-current[21038]: syslog-ng                        RUNNING   pid 33, uptime 0:00:04
dockerd-current[21038]: 
```
No logs (or other files beside JAR) are generated, so I'd assume that java never starts.

Surprisingly enough, the following works:
```
root@host# docker exec -it spigot /bin/bash
root@container# /etc/init.d/minecraft_server status
spigot.jar is not running
root@container# /etc/init.d/minecraft_server start 
Starting minecraft server as user minecraft...Started
root@container# /etc/init.d/minecraft_server status
spigot.jar is running with PID 454
```

Please let me know what other outputs you might need for troubleshooting.

**Comment by minexew** [comment]
Also,
```
root@container# supervisorctl start spigot
spigot: ERROR (spawn error)
```

**Comment by minexew** [comment]
Further clues:
```
root@container# /etc/init.d/minecraft_server status                                                                                                    
spigot.jar is not running
root@container# /waitjava.sh minecraft_server spigot.jar
spigot.jar is already running with PID 935
root@container# /waitjava.sh minecraft_server spigot.jar
spigot.jar is already running with PID 956
root@container# /waitjava.sh minecraft_server spigot.jar
spigot.jar is already running with PID 977
```

**Comment by minexew** [comment]
Bingo:
```
# id minecraft
uid=0(root) gid=0(root) groups=0(root)
```

**Comment by nimmis** [comment]
`My strong suspicion is that ps -u minecraft doesn't do what it's supposed to, and returns the /waitjava script started as root which then matches the grep because its commandline contains spigot.jar`
Where do you get the **ps -u minecraft**? 
The command do **ps -ax** so all processes are shown and the line also have to contain /usr/bin/java 
Where the container is started a script checks that /minecraft folder and the user minecraft have the sam UID
How old is your nimmis/spigot container? Try to do a docker pull nimmis/docker first

**Comment by nimmis** [comment]
I mean **docker pull nimmis/spigot**

**Comment by minexew** [comment]
>Where do you get the ps -u minecraft?

Here:
https://github.com/nimmis/docker-spigot/blob/dc5afd963d4100f9df481e9fd504f56ac530f0c9/rootfs/etc/init.d/minecraft_server#L80

**Comment by minexew** [comment]
I worked around the problem by changing
`grep "$MC_PROC"`
to
`grep "/usr/bin/java"`

**Comment by nimmis** [comment]
Thanks for finding the bug, i have fixed it in the last version including a start/stop bug
so you could just do a pull to get the fixed version

**Comment by minexew** [comment]
Fixed indeed. Thank you :)

**Comment by RedFox122** [comment]
I seam to be having this same issue on Debian 10. any advice to fix?

**Comment by nimmis** [comment]
Did the following:

- a clean install of Debian 10
- installed docker as described [here](https://docs.docker.com/engine/install/debian/)
- mkdir /srv/spigot-data/
- run **docker run -d -p 25565:25565 -e EULA=true --name spigot -v /srv/spigot-data/:/minecraft nimmis/spigot**

Result:
`Success! Everything completed successfully. Copying final .jar files now.
Copying spigot-1.15.2-R0.1-SNAPSHOT.jar to /build-mc/./spigot-1.15.2.jar
  - Saved as ./spigot-1.15.2.jar
*** Running /etc/my_runalways/85_fix_startsh...
start.sh missing, creating link for /minecraft/start.sh
*** Running /etc/my_runalways/90_eula...
*** Running /etc/rc.local...
*** Booting supervisor daemon...
*** Supervisor started as PID 465
2020-06-12 10:12:25,875 CRIT Set uid to user 0
*** Started processes via Supervisor......
crond                            RUNNING   pid 469, uptime 0:00:03
spigot                           RUNNING   pid 470, uptime 0:00:03
syslog-ng                        RUNNING   pid 468, uptime 0:00:03`

What do you mean with **same issue**?
