### ISSUE TITLE
`mc_stop` seems not working

### ISSUE THREAD

**Issue by 0xBADDCAFE** [nimmis/docker-spigot#26]
When execute `mc_stop` it prints `spigot: stopped` and can't execute `mc_stop` again, but clients can login server and do not regenerate files like world or server.properties when execute `mc_start`.

**Comment by nimmis** [comment]
I seems like the problem I fixed yesterday, are you running the latest version as I can't reproduce the problem. 

Instead of executing **mc_start** can you send me the output of the command
**/bin/sh -c 'tail /var/log/supervisor/spigot&#42;'**

**Comment by 0xBADDCAFE** [comment]
> I seems like the problem I fixed yesterday

Oh sorry, I didn't check the latest image and currently it works fine. Thanks.
