### ISSUE TITLE
"/restart" command shuts down the server

### ISSUE THREAD

**Issue by minexew** [nimmis/docker-spigot#28]
Server log:

```
[19:21:09 INFO]: PLAYER_NAME issued server command: /restart
[19:21:09 INFO]: Startup script './start.sh' does not exist! Stopping server.
[19:21:09 INFO]: Stopping server
[19:21:10 INFO]: Saving players
[19:21:11 INFO]: Saving worlds
```

Afterwards, the server is stopped instead of restarting. The container keeps running.

**Comment by nimmis** [comment]
I missed that function, I'll fix it today, a quick fix for you running container is to issue

`docker exec minecraft /bin/sh -c 'ln -s /usr/local/bin/mc_start /minecraft/start.sh'`

where **minecraft** is the name of the spigot container

**Comment by nimmis** [comment]
Now it's a new version with the start.sh issue fixed, use

`docker pull nimmis/spigot`

to get the fixed version

**Comment by minexew** [comment]
Thank you for your work.
