### ISSUE TITLE
First Start fails on timezone setting

### ISSUE THREAD

**Issue by wofnull** [nimmis/docker-spigot#30]
First run / every run failes because the system trys to set a timezone that is neither setable by user or available ( as it seems ) 

Fun Fact, the called file /etc/my_runonce/50_set_timezone , causing the problem is nowhere to be found in the github repo here.

root@Datenspeicher:/sharedfolders/gameservers/minecraft# docker logs -f spigot                                                  
*** open logfile                                                                                                                
*** Run files in /etc/my_runonce/                                                                                               
*** Running /etc/my_runonce/00_dump_info.sh...                                                                                  
Build of nimmis/java:openjdk-8-jdk, date: 2018-01-03T16:00:21Z                                                                  
Build of nimmis/spigot:latest, date: 2018-01-03T16:11:22Z                                                                       
Build of nimmis/ubuntu:16.04, date: 2018-01-03T14:58:34Z                                                                        
*** Running /etc/my_runonce/50_set_timezone...                                                                                  
timezone not set, trying to autodetect                                                                                          
external ip is xx.xxx.xx.xxx                                                                                               
Timezone Europe/Berlin not available on time system                                                                             
*** /etc/my_runonce/50_set_timezone failed with status 1 
                                                                                                                                
*** Killing all processes...

**Comment by wofnull** [comment]
Found the problem:

It seems that this thing was build using an own ubuntu build of this repo owner, however the automatic timezone feature has a several bug:

if the timezone Server is querried for an unknown IP it sends a Timezone in the Format europe\berlin back to the server. it Looks like that at least for europe locations this is not so good, because the Ubuntu timezone tool used does only recognize europa\berlin as correct format.

Workaround for this Docker Container is to set the timezone 
TIMEZONE=EUROPA\BERLIN 
to bring it to work.

this shall be fixxed in nimmis/ubuntu image.

**Comment by nimmis** [comment]
I was already on it but it takes time for the docker-hub to rebuild the whole chain, the problem was 1. that I didn't check the 16.04 version and that one was missing tzdata i.e timezones
2. had a fatal error return in the timezone scripts making the startup process to fail

When the builds are finished there should be no more error regardless of the timezone is correct or not.

**Comment by nimmis** [comment]
if you do

`docker pull nimmis/spigot`

it will work now
