### ISSUE TITLE
Specific Additional Java Opts

### ISSUE THREAD

**Issue by ssshake** [nimmis/docker-spigot#36]
Hi it appears that you abstract the java opts such as xmx. I want to pass in some custom arguments. Could you explain how to properly do that with your image?

These are what I'm trying to do:

`-XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=4M -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts`

**Comment by SILENCE-ETERNAL** [comment]
@ssshake if I'm reading the code right, you aught to be able to inject them right here:

https://github.com/nimmis/docker-spigot/blob/dc0b813cae09f0576d58801a7b4c2000b498d916/rootfs/etc/init.d/minecraft_server#L35

**Comment by nimmis** [comment]
implemented, use -e OTHER_JAVA_OPS=
