### ISSUE TITLE
Mounting persistent world data when server alive

### ISSUE THREAD

**Issue by dkotama** [nimmis/docker-spigot#38]
Hi thank you for making this container,

i want to know the possibilities of backing up my current world,
because the server already running like 1 weeks and for running -v command, it means i must run  a new container

please help thank you

**Comment by recklessop** [comment]
Use docker -lt command to get a bash prompt inside of the container, then copy (via sftp or something) the world data to the docker host. Once you have it on the docker host... in a folder, you can stop the current container. 

Start a new container using -v and point it to the folder that you sftp'd all your data out to.
