### ISSUE TITLE
How to upgrade to 2.13

### ISSUE THREAD

**Issue by ssshake** [nimmis/docker-spigot#39]
Probably a dumb question that's not specific to your image but how do i update the image from 2.12 to 2.13 or to any new version going forward?

**Comment by nimmis** [comment]
No sure what you mean by 2.12 but

upgrade container version do a

docker pull nimmis/spigot

to update version

for minecraft version see command

docker exec -it spigot set_mc_ver <minecraft version> 

in latest release
