### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by signofkoen** [nimmis/docker-spigot#4]
Maybe you can change spigot_init.sh to start.sh because that's the standard .sh file what Spigot will use for restarting the server when it crashes.

Source:
spigot.yml
restart-on-crash: true
restart-script: ./start.sh

**Comment by nimmis** [comment]
As you can see I have removed the start script so it runs as a daemon instead. Supervisord will take care of the automatic restart and also the world data is now flushed to disk when you issues a docker stop command.
