### ISSUE TITLE
How to install plugins

### ISSUE THREAD

**Issue by ChillingCheese** [nimmis/docker-spigot#43]
How do u do the plugins? I have made the server already but Idk where the plugins folder is

**Comment by hannesa2** [comment]
Do you figured out how to do this ?

**Comment by penut85420** [comment]
You need to mount you minecraft directory first, e.g. `-v /home/nimmis/mc-srv:/minecraft`
Run the image and wait for the building done, you'll see the plugin folder under the `/home/nimmis/mc-srv`
Then put your plugins in `/home/nimmis/mc-srv/plugins` and enter command `reload` in game.

**Comment by nimmis** [comment]
@penut85420 answer is ok if you running it on a local disk, a more generic approach is to copy the files thru the conainer filesystem using docker cp command

    docker cp <filename to copy> <spigot container name>:/minecraft/plugins/

and the file will be saved on the correct location, if the container name is **spigot** and the filename is **plugin.jar** then command will be

    docker cp plugin.jar spigot:/minecraft/plugins/
