### ISSUE TITLE
Minecraft 1.17 Support

### ISSUE THREAD

**Issue by afflitto** [nimmis/docker-spigot#45]
Minecraft 1.17 requires Java 16, so Spigot for 1.17 cannot be built in the current docker image. I was able to get around this for now by running
```
apt install openjdk16-jdk
```
in the running docker container.

**Comment by jbarneson** [comment]
apt install openjdk-16-jdk

**Comment by jedrzejowski** [comment]
If anybody is interested, I made a fork of image and updated it to 20.04.
[GitHub](https://github.com/jedrzejowski/docker-spigot) [Docker Hub](https://hub.docker.com/r/ajedrzejowski/spigot)

**Comment by nimmis** [comment]
fixed and updated to ubuntu 20.04/OpenJDK 1.6, pull a new version from hub.docker.com
