### ISSUE TITLE
adoptopenjdk no longer available

### ISSUE THREAD

**Issue by em3e3** [nimmis/docker-spigot#47]
Dockerfile attempts to apt-get adoptopenjdk, which no longer exists.
Suggest apt-get install openjdk-16-jre-headless instead

**Comment by nimmis** [comment]
It works for me (today), what's your setup and the output
openjdk-16-jre-headless would not work as it doesn't contain Java

**Comment by em3e3** [comment]
Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-90-generic x86_64)
Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2

I'm using the snap version of Docker (yes, I know, bad, bad, bad).

Only two versions of jdk in /etc:
drwxr-xr-x 5 root root    4096 Nov 14 02:04 java-16-openjdk
drwxr-xr-x 5 root root    4096 Sep 30  2019 java-8-openjdk

And spigot is running, Minecraft world is accessible.

Here's the error I was getting when running spigot container before installing openjdk:

*** The version you have requested to build requires Java versions between [Java 16, Java 17], but you are using Java 8
*** Please rerun BuildTools using an appropriate Java version. For obvious reasons outdated MC versions do not support Java versions that did not exist at their release.


Here's the command I ran to setup the container:

sudo docker run -d -p 25567:25565 --name spigot2 -e EULA=true -v /home/nimmis/mc-srv2:/minecraft -e MC_MAXMEM-8g nimmis/spigot

Yes, I'm running two spigot containers, each on their own port.

**Comment by nimmis** [comment]
you have probably an old cached version of nimmis/spigot
running

    docker run nimmis/spigot  cat /etc/BUILDS/spigot

shoudl give the following output if you are using the latest version

     Build of nimmis/spigot:latest, date: 2021-07-04T18:54:09Z

If not try to do

    docker pull nimmis/spigot

**Comment by em3e3** [comment]
Yep, old version:

Build of nimmis/spigot:latest, date: 2019-09-30T19:54:49Z

sudo docker pull nimmis/spigot
Status: Downloaded newer image for nimmis/spigot:latest
docker.io/nimmis/spigot:latest

Build of nimmis/spigot:latest, date: 2021-07-04T18:54:09Z

What's strange is that it actually worked, once.  That threw me off, as well as still learning Docker.  Created a new container after the pull, and it's running.  Closing the ticket.  Thanks!
