### ISSUE TITLE
Java Version 8 not supported - Error during installation of latest version of spigot

### ISSUE THREAD

**Issue by adem1on** [nimmis/docker-spigot#48]
Hi,
tried to set up a new world. Deleted my local directory and started the container with:
docker run -d -p 16566:25565 -e EULA=true --name spigot -v /media/MC/spigot:/minecraft nimmis/spigot

Error message: 
...
Attempting to build version: 'latest' use --rev <version> to override
Found version
{
        "name": "3284",
        "description": "Jenkins build 3284",
        "refs": {
                "BuildData": "a4785704979a469daa2b7f6826c84e7fe886bb03",
                "Bukkit": "d32e3c764edd6a449ddd220720185d266c2193f9",
                "CraftBukkit": "0ebef35c7273aec7fbeb76e3e4f8ac18eda858c7",
                "Spigot": "38929296b008a62a7a8532c46550aa493e2246a8"
        },
        "toolsVersion": 128,
        "javaVersions": [60, 61]
}

*** The version you have requested to build requires Java versions between [Java 16, Java 17], but you are using Java 8
*** Please rerun BuildTools using an appropriate Java version. For obvious reasons outdated MC versions do not support Java versions that did not exist at their release.
cp: cannot stat '/minecraft/build/Spigot/Spigot-Server/target/spigot-*.jar': No such file or directory
*** Running /etc/my_runalways/90_eula...
*** Running /etc/rc.local...
*** Booting supervisor daemon...
*** Supervisor started as PID 94
2021-11-22 10:19:29,670 CRIT Set uid to user 0
*** Started processes via Supervisor......
crond                            RUNNING   pid 98, uptime 0:00:04
spigot                           BACKOFF   Exited too quickly (process log may have details)
syslog-ng                        RUNNING   pid 97, uptime 0:00:04

OS/Docker Versions:
Docker version 17.05.0-ce, build 89658be
Description:    Ubuntu 20.04.3 LTS

Did I made an obvious mistake (It's some time now since I created a new container)?

**Comment by nimmis** [comment]
you have probably an old cached version of nimmis/spigot
running

    docker run nimmis/spigot  cat /etc/BUILDS/spigot

shoudl give the following output if you are using the latest version

     Build of nimmis/spigot:latest, date: 2021-07-04T18:54:09Z

If not try to do

    docker pull nimmis/spigot

**Comment by adem1on** [comment]
the docker pull did the trick, thank you!
