### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by guFalcon** [nimmis/docker-spigot#53]
Sorry to report this, but this just cost me an hour (shame on me).

The line:
Need -e SPIGOT_VERSION=1.18 
tells everyone to add SPIGOT_VERSION to their startup-environment, when in fact it's
SPIGOT_VER=1.18
you're listening to in your script.

**Comment by nimmis** [comment]
Many thanks for notice me about the writing error, fixed it instant it so no more people need to be confused
